services:
  frontend:
    build:
      dockerfile: ./dockerfile.frontend
      context: .
    container_name: redTetris-frontend
    ports:
      - 5173:5173
    networks:
      - redTetris
    volumes:
      - ./my-app:/my-app
      # - /my-app/node_modules
    restart: always
    working_dir: /my-app
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      dockerfile: ./dockerfile.backend
      context: ./
    container_name: redTetris-backend
    ports:
      - 3000:3000
    restart: "always"
    networks:
      - redTetris
    volumes:
      - ./server:/server
      # - /app/node_modules
    working_dir: /server
    command: ["yarn", "run", "start:dev"]

  test:
    build:
      dockerfile: ./dockerfile.test
      context: .
    container_name: redTetris-test
    ports:
      - 3001:5173
    restart: "always"
    networks:
      - redTetris
    volumes:
      - ./test:/test

networks:
  redTetris:
    driver: bridge
