services:
  frontend:
    build:
      dockerfile: dockerfile.frontend
      context: .
    container_name: redTetris-frontend
    ports:
      - 5173:5173
    networks:
      - redTetris
    volumes:
      - ./my-app:/my-app
      # - /my-app/node_modules
    restart: always

  backend:
    build:
      dockerfile: ./dockerfile.backend
      context: .
    container_name: redTetris-backend
    ports:
      - 3000:3000
    restart: "always"
    networks:
      - redTetris
    volumes:
      - ./server:/server
      # - /app/node_modules

networks:
  redTetris:
    driver: bridge
